[package]
name = "configuration-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
csv = "1.3.1"
ini = "1.3.0"
serde = { version = "1.0.216", features = ["derive"] }
thiserror = "2.0.6"
