name: Build with CentOS 7 and devtoolset-7

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/frun36/cc7-fit

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: 'false'  # We'll manually initialize submodules

      - name: Configure Git for GitLab Authentication
        run: |
          git config --global url."https://${GITLAB_USERNAME}:${GITLAB_ACCESS_TOKEN}@gitlab.com/".insteadOf "https://gitlab.com/"

        env:
          GITLAB_USERNAME: ${{ secrets.GITLAB_USERNAME }}
          GITLAB_ACCESS_TOKEN: ${{ secrets.GITLAB_ACCESS_TOKEN }}

      - name: Initialize and Update Submodules
        run: |
          git submodule update --init --recursive

      - name: Build with CMake and Make
        run: |
          source /opt/rh/devtoolset-7/enable
          cd core
          cmake3 . -DMAPI=1
          make -j$(nproc)
